/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlidesSlide1RouteImport } from './routes/slides/slide1'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlidesSlide1Route = SlidesSlide1RouteImport.update({
  id: '/slides/slide1',
  path: '/slides/slide1',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/slides/slide1': typeof SlidesSlide1Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/slides/slide1': typeof SlidesSlide1Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/slides/slide1': typeof SlidesSlide1Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/slides/slide1'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/slides/slide1'
  id: '__root__' | '/' | '/slides/slide1'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlidesSlide1Route: typeof SlidesSlide1Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slides/slide1': {
      id: '/slides/slide1'
      path: '/slides/slide1'
      fullPath: '/slides/slide1'
      preLoaderRoute: typeof SlidesSlide1RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlidesSlide1Route: SlidesSlide1Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
